routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DiagnosaController;
use App\Http\Controllers\Admin\GejalaController;
use App\Http\Controllers\Admin\JenisAutisController;
use App\Http\Controllers\Admin\KriteriaController;
use App\Http\Controllers\Admin\LokasiPengobatanController;
use App\Http\Controllers\Admin\PerhitunganController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\DashboardController as UserDashboardController;
use App\Http\Controllers\User\DiagnosaController as UserDiagnosaController;
use App\Http\Controllers\User\ProfileController as UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth', 'role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');

    Route::resource('jenis-autis', JenisAutisController::class);
    Route::get('/jenis-autis/gejala/{jenis_auti}', [JenisAutisController::class, 'gejala'])->name('jenis-autis.gejala');
    Route::put('/jenis-autis/gejala/{jenis_auti}', [JenisAutisController::class, 'simpanGejala'])->name('jenis-autis.gejala');

    Route::resource('gejala', GejalaController::class);
    Route::resource('kriteria', KriteriaController::class)->except('show');

    Route::controller(PerhitunganController::class)->prefix('perhitungan')->as('perhitungan.')->group(function () {
        Route::get('/pilih-gejala', 'pilihGejala')->name('pilih-gejala');
        Route::post('/perhitungan', 'perhitungan')->name('perhitungan');
        Route::post('/simpan', 'simpan')->name('simpan');
    });

    Route::resource('diagnosa', DiagnosaController::class)->only('index', 'show', 'destroy');
    Route::resource('lokasi-pengobatan', LokasiPengobatanController::class);
});

Route::group(['middleware' => ['auth', 'role:user'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
    Route::resource('diagnosa', UserDiagnosaController::class)->except('edit', 'update', 'destroy');

    Route::get('/profile', [UserProfileController::class, 'index'])->name('profile.index');
    Route::put('/profile', [UserProfileController::class, 'update'])->name('profile.update');
});

require __DIR__ . '/auth.php';

resources/views/layouts/includes/admin/footer.blade.php
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2024. Sistem Pakar Diagnosa Autisme</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"><i class="ti-heart text-danger ml-1"></i> Nofa Rima Yanti Nasution</span>
    </div>
</footer>

resources/views/layouts/includes/admin/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item {{ activeClass('admin.dashboard') }}">
            <a class="nav-link" href="{{ route('admin.dashboard') }}">
                <i class="icon-grid menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>

        <li class="nav-item nav-title mt-3">
            Master Data
        </li>

        <li class="nav-item {{ activeClass('admin.jenis-autis.*') }}">
            <a class="nav-link" href="{{ route('admin.jenis-autis.index') }}">
                <i class="icon-grid menu-icon"></i>
                <span class="menu-title">Jenis Autis</span>
            </a>
        </li>

        <li class="nav-item {{ activeClass('admin.gejala.*') }}">
            <a class="nav-link" href="{{ route('admin.gejala.index') }}">
                <i class="icon-grid menu-icon"></i>
                <span class="menu-title">Gejala</span>
            </a>
        </li>

        <li class="nav-item {{ activeClass('admin.kriteria.*') }}">
            <a class="nav-link" href="{{ route('admin.kriteria.index') }}">
                <i class="icon-grid menu-icon"></i>
                <span class="menu-title">Kriteria</span>
            </a>
        </li>

        <li class="nav-item {{ activeClass('admin.lokasi-pengobatan.*') }}">
            <a class="nav-link" href="{{ route('admin.lokasi-pengobatan.index') }}">
                <i class="icon-grid menu-icon"></i>
                <span class="menu-title">Lokasi Pengobatan</span>
            </a>
        </li>

        <li class="nav-item nav-title mt-3">
            Uji Perhitungan
        </li>

        <li class="nav-item {{ activeClass('admin.perhitungan.*') }}">
            <a class="nav-link" href="{{ route('admin.perhitungan.pilih-gejala') }}">
                <i class="icon-grid menu-icon"></i>
                <span class="menu-title">Perhitungan</span>
            </a>
        </li>

        <li class="nav-item nav-title mt-3">
            User
        </li>

        <li class="nav-item {{ activeClass('admin.diagnosa.*') }}">
            <a class="nav-link" href="{{ route('admin.diagnosa.index') }}">
                <i class="icon-grid menu-icon"></i>
                <span class="menu-title">Diagnosa</span>
            </a>
        </li>
    </ul>
</nav>

resources/views/layouts/includes/admin/topbar.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo mr-5" href="{{ route('home') }}"><img src="{{ asset('assets/images/logo.png') }}"
                class="mr-2" alt="logo" /></a>
        <a class="navbar-brand brand-logo-mini" href="{{ route('home') }}"><img
                src="{{ asset('assets/images/icon.png') }}" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="icon-menu"></span>
        </button>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                    <img src="{{ auth()->user()->getProfilePicture() }}" alt="profile" />
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="{{ route('admin.profile.index') }}">
                        <i class="ti-settings text-primary"></i>
                        Profil
                    </a>
                    <a class="dropdown-item logout-link">
                        <i class="ti-power-off text-primary"></i>
                        Keluar
                    </a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
            data-toggle="offcanvas">
            <span class="icon-menu"></span>
        </button>
    </div>
</nav>