routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DiagnosaController;
use App\Http\Controllers\Admin\GejalaController;
use App\Http\Controllers\Admin\JenisAutisController;
use App\Http\Controllers\Admin\KriteriaController;
use App\Http\Controllers\Admin\LokasiPengobatanController;
use App\Http\Controllers\Admin\PerhitunganController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\DashboardController as UserDashboardController;
use App\Http\Controllers\User\DiagnosaController as UserDiagnosaController;
use App\Http\Controllers\User\ProfileController as UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth', 'role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');

    Route::resource('jenis-autis', JenisAutisController::class);
    Route::get('/jenis-autis/gejala/{jenis_auti}', [JenisAutisController::class, 'gejala'])->name('jenis-autis.gejala');
    Route::put('/jenis-autis/gejala/{jenis_auti}', [JenisAutisController::class, 'simpanGejala'])->name('jenis-autis.gejala');

    Route::resource('gejala', GejalaController::class);
    Route::resource('kriteria', KriteriaController::class)->except('show');

    Route::controller(PerhitunganController::class)->prefix('perhitungan')->as('perhitungan.')->group(function () {
        Route::get('/pilih-gejala', 'pilihGejala')->name('pilih-gejala');
        Route::post('/perhitungan', 'perhitungan')->name('perhitungan');
        Route::post('/simpan', 'simpan')->name('simpan');
    });

    Route::resource('diagnosa', DiagnosaController::class)->only('index', 'show', 'destroy');
    Route::resource('lokasi-pengobatan', LokasiPengobatanController::class);
});

Route::group(['middleware' => ['auth', 'role:user'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
    Route::resource('diagnosa', UserDiagnosaController::class)->except('edit', 'update', 'destroy');

    Route::get('/profile', [UserProfileController::class, 'index'])->name('profile.index');
    Route::put('/profile', [UserProfileController::class, 'update'])->name('profile.update');
});

require __DIR__ . '/auth.php';

app/Models/Gejala.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Gejala extends Model
{
    use HasFactory;

    /**
     * Tabel yang digunakan model
     *
     * @var string
     */
    protected $table = 'tb_gejala';

    /**
     * Tabel tidak memiliki kolom waktu (created_at dan updated_at)
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * Kolom tabel
     *
     * @var array
     */
    protected $fillable = [
        'kode',
        'gejala',
        'bobot',
    ];

    /**
     * Relasi Many to Many ke tabel Jenis_autis
     * 
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function jenisAutis()
    {
        return $this->belongsToMany(Jenis_autis::class, 'tb_gejala_autis', 'id_gejala', 'id_jenis');
    }
}

app/Http/Controllers/Admin/GejalaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Gejala;
use Illuminate\Http\Request;

class GejalaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = Gejala::orderBy('kode')->get();

        return view('admin.gejala.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.gejala.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'kode' => 'required|string|max:4|unique:tb_gejala,kode',
            'gejala' => 'required',
            'bobot' => 'required|numeric',
        ]);

        Gejala::create($request->all());

        return redirect()
            ->route('admin.gejala.index')
            ->withSuccess('Berhasil menambah data gejala baru');
    }

    /**
     * Display the specified resource.
     */
    public function show(Gejala $gejala)
    {
        return view('admin.gejala.show', compact('gejala'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Gejala $gejala)
    {
        return view('admin.gejala.edit', compact('gejala'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Gejala $gejala)
    {
        $request->validate([
            'kode' => 'required|string|max:4|unique:tb_gejala,kode,' . $gejala->id,
            'gejala' => 'required',
            'bobot' => 'required|numeric',
        ]);

        $gejala->update($request->all());

        return redirect()
            ->route('admin.gejala.show', $gejala)
            ->withSuccess('Berhasil memperbarui data gejala');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Gejala $gejala)
    {
        $gejala->delete();

        return redirect()
            ->route('admin.gejala.index')
            ->withSuccess('Berhasil menghapus data gejala');
    }
}

resources/views/admin/gejala/create.blade.php
@extends('layouts.admin')
@section('title', 'Tambah Data Gejala')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 mb-3">
                <div class="d-flex justify-content-between">
                    <h3 class="font-weight-bold">Tambah Data Gejala</h3>

                    <a href="{{ route('admin.gejala.index') }}" class="btn btn-primary btn-sm">
                        Kembali
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{ route('admin.gejala.store') }}" method="post">
                        <div class="card-body">
                            <h4 class="card-title">Data Gejala</h4>

                            @csrf

                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="kode">Kode</label>
                                        <input type="text" name="kode"
                                            class="form-control @error('kode') is-invalid @enderror" id="kode"
                                            value="{{ old('kode') }}" placeholder="Kode" maxlength="4" required>

                                        @error('kode')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="bobot">Bobot</label>
                                        <input type="text" name="bobot"
                                            class="form-control @error('bobot') is-invalid @enderror" id="bobot"
                                            value="{{ old('bobot') }}" placeholder="Bobot" maxlength="255" required>

                                        @error('bobot')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="gejala">Gejala</label>
                                <textarea name="gejala" class="form-control @error('gejala') is-invalid @enderror" id="gejala" placeholder="Gejala" rows="5"
                                    required>{{ old('gejala') }}</textarea>

                                @error('gejala')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-end">
                            <input type="submit" value="Simpan" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/gejala/edit.blade.php
@extends('layouts.admin')
@section('title', 'Edit Data Gejala')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 mb-3">
                <div class="d-flex justify-content-between">
                    <h3 class="font-weight-bold">Edit Data Gejala</h3>

                    <a href="{{ route('admin.gejala.index') }}" class="btn btn-primary btn-sm">
                        Kembali
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{ route('admin.gejala.update', $gejala) }}" method="post">
                        <div class="card-body">
                            <h4 class="card-title">Data Gejala</h4>

                            @csrf
                            @method('PUT')

                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="kode">Kode</label>
                                        <input type="text" name="kode"
                                            class="form-control @error('kode') is-invalid @enderror" id="kode"
                                            value="{{ old('kode', $gejala->kode) }}" placeholder="Kode" maxlength="4" required>

                                        @error('kode')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="bobot">Bobot</label>
                                        <input type="text" name="bobot"
                                            class="form-control @error('bobot') is-invalid @enderror" id="bobot"
                                            value="{{ old('bobot', $gejala->bobot) }}" placeholder="Bobot" maxlength="255" required>

                                        @error('bobot')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="gejala">Gejala</label>
                                <textarea name="gejala" class="form-control @error('gejala') is-invalid @enderror" id="gejala" placeholder="Gejala" rows="5"
                                    required>{{ old('gejala', $gejala->gejala) }}</textarea>

                                @error('gejala')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-end">
                            <input type="submit" value="Simpan" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/gejala/index.blade.php
@extends('layouts.admin')
@section('title', 'Kelola Data Gejala')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 mb-3">
                <div class="d-flex justify-content-between">
                    <h3 class="font-weight-bold">Kelola Data Gejala</h3>

                    <a href="{{ route('admin.gejala.create') }}" class="btn btn-primary btn-sm">
                        Tambah
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Daftar Gejala</h4>
                        <div class="table-responsive">
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Kode</th>
                                        <th>Gejala</th>
                                        <th>Bobot</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($data as $item)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->kode }}</td>
                                            <td>{{ \Str::limit($item->gejala, 120) }}</td>
                                            <td>{{ $item->bobot }}</td>
                                            <td class="d-flex justify-content-end">
                                                <a href="{{ route('admin.gejala.show', $item) }}"
                                                    class="btn btn-sm btn-success">Lihat</a>
                                                <a href="{{ route('admin.gejala.edit', $item) }}"
                                                    class="btn btn-sm btn-warning mx-1">Edit</a>
                                                <a href="#" class="btn btn-sm btn-danger btn-delete"
                                                    data-id="{{ $item->id }}">Hapus</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('custom_html')
    <form action="#" method="post" id="delete-form">
        @csrf
        @method('DELETE')
    </form>
@endsection

@push('custom_js')
    <script>
        let deleteBtns = document.querySelectorAll('.btn-delete');
        deleteBtns.forEach((btn) => {
            btn.addEventListener('click', () => {
                let id = btn.getAttribute('data-id');

                Swal.fire({
                    title: 'Yakin Ingin Menghapus?',
                    text: "Yakin ingin menghapus data? Data yang dihapus tidak bisa dikembalikan lagi.",
                    icon: 'warning',
                    showCancelButton: true,
                    cancelButtonColor: '#3085d6',
                    confirmButtonColor: '#d33',
                    confirmButtonText: 'Hapus',
                    cancelButtonText: 'Batal',
                }).then((result) => {
                    if (result.isConfirmed) {
                        let form = document.querySelector('#delete-form');
                        form.setAttribute('action',
                            `{{ route('admin.gejala.destroy', false) }}/${id}`);

                        form.submit();
                    }
                })
            });
        });
    </script>
@endpush

resources/views/admin/gejala/show.blade.php
@extends('layouts.admin')
@section('title', 'Data Gejala')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 mb-3">
                <div class="d-flex justify-content-between">
                    <h3 class="font-weight-bold">Data Gejala</h3>

                    <a href="{{ route('admin.gejala.index') }}" class="btn btn-primary btn-sm">
                        Kembali
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Data Gejala</h4>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>ID</td>
                                        <td><strong>{{ $gejala->id }}</strong></td>
                                    </tr>
                                    <tr>
                                        <td>Kode</td>
                                        <td><strong>{{ $gejala->kode }}</strong></td>
                                    </tr>
                                    <tr>
                                        <td>Bobot</td>
                                        <td><strong>{{ $gejala->bobot }}</strong></td>
                                    </tr>
                                    <tr>
                                        <td>Gejala</td>
                                        <td><strong>{{ $gejala->gejala }}</strong></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer d-flex justify-content-end">
                        <a href="{{ route('admin.gejala.edit', $gejala) }}" class="btn btn-warning mr-1 btn-sm">Edit</a>
                        <a href="#" class="btn btn-danger btn-delete btn-sm">Hapus</a>
                    </div>
                </div>

                <div class="card mt-3">
                    <div class="card-body">
                        <h4 class="card-title">Jenis Autis</h4>
                        <p>Jenis autis yang memiliki gejala ini</p>
                        <div class="table-responsive">
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nama</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($gejala->jenisAutis as $item)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->nama }}</td>
                                            <td class="d-flex justify-content-end">
                                                <a href="{{ route('admin.jenis-autis.show', $item) }}" class="btn btn-sm btn-success">Lihat</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('custom_html')
    <form action="{{ route('admin.gejala.destroy', $gejala) }}" method="post" id="delete-form">
        @csrf
        @method('DELETE')
    </form>
@endsection

@push('custom_js')
    <script>
        let deleteBtn = document.querySelector('.btn-delete');
        deleteBtn.addEventListener('click', () => {

            Swal.fire({
                title: 'Yakin Ingin Menghapus?',
                text: "Yakin ingin menghapus data? Data yang dihapus tidak bisa dikembalikan lagi.",
                icon: 'warning',
                showCancelButton: true,
                cancelButtonColor: '#3085d6',
                confirmButtonColor: '#d33',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal',
            }).then((result) => {
                if (result.isConfirmed) {
                    let form = document.querySelector('#delete-form');
                    form.submit();
                }
            })
        });
    </script>
@endpush