routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DiagnosaController;
use App\Http\Controllers\Admin\GejalaController;
use App\Http\Controllers\Admin\JenisAutisController;
use App\Http\Controllers\Admin\KriteriaController;
use App\Http\Controllers\Admin\LokasiPengobatanController;
use App\Http\Controllers\Admin\PerhitunganController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\DashboardController as UserDashboardController;
use App\Http\Controllers\User\DiagnosaController as UserDiagnosaController;
use App\Http\Controllers\User\ProfileController as UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth', 'role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');

    Route::resource('jenis-autis', JenisAutisController::class);
    Route::get('/jenis-autis/gejala/{jenis_auti}', [JenisAutisController::class, 'gejala'])->name('jenis-autis.gejala');
    Route::put('/jenis-autis/gejala/{jenis_auti}', [JenisAutisController::class, 'simpanGejala'])->name('jenis-autis.gejala');

    Route::resource('gejala', GejalaController::class);
    Route::resource('kriteria', KriteriaController::class)->except('show');

    Route::controller(PerhitunganController::class)->prefix('perhitungan')->as('perhitungan.')->group(function () {
        Route::get('/pilih-gejala', 'pilihGejala')->name('pilih-gejala');
        Route::post('/perhitungan', 'perhitungan')->name('perhitungan');
        Route::post('/simpan', 'simpan')->name('simpan');
    });

    Route::resource('diagnosa', DiagnosaController::class)->only('index', 'show', 'destroy');
    Route::resource('lokasi-pengobatan', LokasiPengobatanController::class);
});

Route::group(['middleware' => ['auth', 'role:user'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
    Route::resource('diagnosa', UserDiagnosaController::class)->except('edit', 'update', 'destroy');

    Route::get('/profile', [UserProfileController::class, 'index'])->name('profile.index');
    Route::put('/profile', [UserProfileController::class, 'update'])->name('profile.update');
});

require __DIR__ . '/auth.php';

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')
@section('title', 'Admin Dashboard')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin">
                <h3 class="font-weight-bold">Selamat Datang {{ auth()->user()->name }}</h3>
                <h6 class="font-weight-normal mb-0">
                    Sistem Pakar Diagnosa Autisme
                </h6>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-md-3 mb-4 stretch-card transparent">
                <div class="card card-tale">
                    <div class="card-body">
                        <p class="mb-4">Jenis Autis</p>
                        <p class="fs-30 mb-2">{{ $count['jenis_autis'] }}</p>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-3 mb-4 stretch-card transparent">
                <div class="card card-dark-blue">
                    <div class="card-body">
                        <p class="mb-4">Gejala</p>
                        <p class="fs-30 mb-2">{{ $count['gejala'] }}</p>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-3 mb-4 stretch-card transparent">
                <div class="card card-light-blue">
                    <div class="card-body">
                        <p class="mb-4">User</p>
                        <p class="fs-30 mb-2">{{ $count['user'] }}</p>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-3 mb-4 stretch-card transparent">
                <div class="card card-dark-blue">
                    <div class="card-body">
                        <p class="mb-4">Diagnosa</p>
                        <p class="fs-30 mb-2">{{ $count['diagnosa'] }}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <p class="card-title">Perhitungan Terbaru</p>

                            @if (count($diagnosa) > 5)
                                <a href="{{ route('admin.diagnosa.index') }}" class="btn btn-sm btn-primary btn-30">Lihat
                                    Semua
                                    &rarr;</a>
                            @endif
                        </div>

                        @if (count($diagnosa) > 0)
                            <div class="table-responsive">
                                <table class="table table-striped table-borderless">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>User</th>
                                            <th>Tanggal</th>
                                            <th>Hasil</th>
                                            <th>Nilai</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($diagnosa as $item)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $item->user->name }}</td>
                                                <td>{{ $item->created_at->translatedFormat('l, d F Y H:i') }}</td>
                                                <td>{{ $item->jenisAutis->nama }}</td>
                                                <td>{{ $item->nilai }}</td>
                                                <td class="text-right">
                                                    <a href="{{ route('admin.diagnosa.show', $item) }}"
                                                        class="btn btn-primary btn-sm">Lihat</a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        @else
                            <div class="alert alert-info">
                                Tidak ada data untuk ditampilkan.
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('custom_js')
    <script src="{{ asset('assets/themes/skydash/js/dashboard.js') }}"></script>
@endpush

resources/views/admin/profile.blade.php
@extends('layouts.admin')
@section('title', 'Profil Saya')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="d-flex justify-content-center h-100">
                                    <div class="align-self-center text-center">
                                        <img src="{{ auth()->user()->getProfilePicture() }}" alt="Foto Profil"
                                            class="img-lg rounded-circle mb-3" />
                                        <div class="mb-3">
                                            <h3>{{ auth()->user()->name }}</h3>
                                        </div>
                                        <p>{{ auth()->user()->email }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="card">
                                    <form action="{{ route('admin.profile.update') }}" method="post"
                                        enctype="multipart/form-data">
                                        @csrf
                                        @method('PUT')

                                        <div class="card-body">
                                            <h4 class="card-title">Edit Profil</h4>

                                            @if (auth()->user()->email_verified_at == null)
                                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                                    Email belum terverifikasi. Kami telah mengirim tautan konfirmasi ke
                                                    email tersebut.

                                                    <button type="button" class="close" data-dismiss="alert"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                            @endif

                                            <div class="form-group">
                                                <label for="nama">Nama</label>
                                                <input type="text" name="name"
                                                    class="form-control @error('name') is-invalid @enderror" id="nama"
                                                    value="{{ old('name', auth()->user()->name) }}" placeholder="Nama"
                                                    minlength="4" maxlength="255" required>

                                                @error('name')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>

                                            <div class="form-group">
                                                <label for="file">Foto Profil</label>
                                                <input type="file" name="picture"
                                                    class="form-control @error('picture') is-invalid @enderror"
                                                    id="file">

                                                @error('picture')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>

                                            <div class="row">
                                                <div class="col-12 col-md-6">
                                                    <div class="form-group">
                                                        <label for="email">Email</label>
                                                        <input type="email" name="email"
                                                            class="form-control @error('email') is-invalid @enderror"
                                                            id="nama"
                                                            value="{{ old('email', auth()->user()->email) }}"
                                                            placeholder="Email" minlength="12" maxlength="255" required>

                                                        @error('email')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                    </div>
                                                </div>
                                                <div class="col-12 col-md-6">
                                                    <div class="form-group">
                                                        <label for="nama">Password</label>
                                                        <input type="password" name="password"
                                                            class="form-control @error('password') is-invalid @enderror"
                                                            id="password" value="{{ old('password') }}"
                                                            placeholder="Password" minlength="8" maxlength="255">

                                                        @error('password')
                                                            <span class="invalid-feedback" role="alert">
                                                                <strong>{{ $message }}</strong>
                                                            </span>
                                                        @enderror
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="d-flex justify-content-end">
                                                <input type="submit" class="btn btn-primary" value="Simpan">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection