routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DiagnosaController;
use App\Http\Controllers\Admin\GejalaController;
use App\Http\Controllers\Admin\JenisAutisController;
use App\Http\Controllers\Admin\KriteriaController;
use App\Http\Controllers\Admin\LokasiPengobatanController;
use App\Http\Controllers\Admin\PerhitunganController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\DashboardController as UserDashboardController;
use App\Http\Controllers\User\DiagnosaController as UserDiagnosaController;
use App\Http\Controllers\User\ProfileController as UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth', 'role:admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile.index');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');

    Route::resource('jenis-autis', JenisAutisController::class);
    Route::get('/jenis-autis/gejala/{jenis_auti}', [JenisAutisController::class, 'gejala'])->name('jenis-autis.gejala');
    Route::put('/jenis-autis/gejala/{jenis_auti}', [JenisAutisController::class, 'simpanGejala'])->name('jenis-autis.gejala');

    Route::resource('gejala', GejalaController::class);
    Route::resource('kriteria', KriteriaController::class)->except('show');

    Route::controller(PerhitunganController::class)->prefix('perhitungan')->as('perhitungan.')->group(function () {
        Route::get('/pilih-gejala', 'pilihGejala')->name('pilih-gejala');
        Route::post('/perhitungan', 'perhitungan')->name('perhitungan');
        Route::post('/simpan', 'simpan')->name('simpan');
    });

    Route::resource('diagnosa', DiagnosaController::class)->only('index', 'show', 'destroy');
    Route::resource('lokasi-pengobatan', LokasiPengobatanController::class);
});

Route::group(['middleware' => ['auth', 'role:user'], 'prefix' => 'user', 'as' => 'user.'], function () {
    Route::get('/dashboard', [UserDashboardController::class, 'index'])->name('dashboard');
    Route::resource('diagnosa', UserDiagnosaController::class)->except('edit', 'update', 'destroy');

    Route::get('/profile', [UserProfileController::class, 'index'])->name('profile.index');
    Route::put('/profile', [UserProfileController::class, 'update'])->name('profile.update');
});

require __DIR__ . '/auth.php';

app/Models/Lokasi_pengobatan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Lokasi_pengobatan extends Model
{
    use HasFactory;

    /**
     * Tabel yang digunakan model
     *
     * @var string
     */
    protected $table = 'tb_lokasi_pengobatan';

    /**
     * Tabel tidak memiliki kolom waktu (created_at dan updated_at)
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * Kolom tabel
     *
     * @var array
     */
    protected $fillable = [
        'nama',
        'alamat',
        'keterangan',
        'latitude',
        'longitude',
    ];
}

app/Http/Controllers/Admin/LokasiPengobatanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Lokasi_pengobatan;
use Illuminate\Http\Request;

class LokasiPengobatanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = Lokasi_pengobatan::orderBy('nama')->get();

        return view('admin.lokasi-pengobatan.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.lokasi-pengobatan.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|string|max:255|unique:tb_lokasi_pengobatan,nama',
            'alamat' => 'nullable|string',
            'keterangan' => 'nullable|string',
            'latitude' => 'nullable|string',
            'longitude' => 'nullable|string',
        ]);

        $lokasi_pengobatan = Lokasi_pengobatan::create($request->all());

        return redirect()
            ->route('admin.lokasi-pengobatan.show', $lokasi_pengobatan)
            ->withSuccess('Berhasil menambah lokasi pengobatan baru');
    }

    /**
     * Display the specified resource.
     */
    public function show(Lokasi_pengobatan $lokasi_pengobatan)
    {
        return view('admin.lokasi-pengobatan.show', compact('lokasi_pengobatan'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Lokasi_pengobatan $lokasi_pengobatan)
    {
        return view('admin.lokasi-pengobatan.edit', compact('lokasi_pengobatan'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Lokasi_pengobatan $lokasi_pengobatan)
    {
        $request->validate([
            'nama' => 'required|string|max:255|unique:tb_lokasi_pengobatan,nama,' . $lokasi_pengobatan->id,
            'alamat' => 'nullable|string',
            'keterangan' => 'nullable|string',
            'latitude' => 'nullable|string',
            'longitude' => 'nullable|string',
        ]);

        $lokasi_pengobatan->update($request->all());

        return redirect()
            ->route('admin.lokasi-pengobatan.show', $lokasi_pengobatan)
            ->withSuccess('Berhasil memperbarui data lokasi pengobatan');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Lokasi_pengobatan $lokasi_pengobatan)
    {
        $lokasi_pengobatan->delete();

        return redirect()
            ->route('admin.lokasi-pengobatan.index')
            ->withSuccess('Berhasil menghapus data lokasi pengobatan');
    }
}

resources/views/admin/lokasi-pengobatan/create.blade.php
@extends('layouts.admin')
@section('title', 'Tambah Data Lokasi Pengobatan')

@section('custom_head')
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />

    <style>
        #map {
            height: 600px;
            border-radius: 8px
        }
    </style>
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 mb-3">
                <div class="d-flex justify-content-between">
                    <h3 class="font-weight-bold">Tambah Data Lokasi Pengobatan</h3>

                    <a href="{{ route('admin.lokasi-pengobatan.index') }}" class="btn btn-primary btn-sm">
                        Kembali
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{ route('admin.lokasi-pengobatan.store') }}" method="post">
                        <div class="card-body">
                            <h4 class="card-title">Data Lokasi Pengobatan</h4>

                            @csrf

                            <div class="form-group">
                                <label for="nama">Nama</label>
                                <input type="text" name="nama"
                                    class="form-control @error('nama') is-invalid @enderror" id="nama"
                                    value="{{ old('nama') }}" placeholder="Nama" required>

                                @error('nama')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="alamat">Alamat</label>
                                        <textarea name="alamat" class="form-control @error('alamat') is-invalid @enderror" id="alamat" placeholder="Alamat">{{ old('alamat') }}</textarea>

                                        @error('alamat')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="keterangan">Keterangan</label>
                                        <textarea name="keterangan" class="form-control @error('keterangan') is-invalid @enderror" id="keterangan"
                                            placeholder="Keterangan">{{ old('keterangan') }}</textarea>

                                        @error('bobot')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="latitude">Latitude</label>
                                        <input type="text" name="latitude"
                                            class="form-control @error('latitude') is-invalid @enderror" id="latitude"
                                            value="{{ old('latitude') }}" placeholder="Latitude">

                                        @error('latitude')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="longitude">Longitude</label>
                                        <input type="text" name="longitude"
                                            class="form-control @error('longitude') is-invalid @enderror" id="longitude"
                                            value="{{ old('longitude') }}" placeholder="Longitude">

                                        @error('longitude')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <div id="map"></div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-end">
                            <input type="submit" value="Simpan" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('custom_js')
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>

    <script>
        let lat = document.querySelector('#latitude');
        let lng = document.querySelector('#longitude');

        var map = L.map('map').setView([-3.7982977, 102.2682549], 14);

        map.attributionControl.setPrefix('')
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);

        var geocoder = L.Control.geocoder({
                defaultMarkGeocode: false
            })
            .on('markgeocode', function(e) {
                var bbox = e.geocode.bbox;
                var poly = L.polygon([
                    bbox.getSouthEast(),
                    bbox.getNorthEast(),
                    bbox.getNorthWest(),
                    bbox.getSouthWest()
                ]).addTo(map);
                map.fitBounds(poly.getBounds());
            })
            .addTo(map);

        var markers = L.layerGroup().addTo(map);

        map.on('click', (event) => {
            markers.clearLayers();
            L.marker([event.latlng.lat, event.latlng.lng]).addTo(markers);

            lat.value = event.latlng.lat;
            lng.value = event.latlng.lng;
        });
    </script>
@endpush

resources/views/admin/lokasi-pengobatan/edit.blade.php
@extends('layouts.admin')
@section('title', 'Edit Data Lokasi Pengobatan')

@section('custom_head')
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />

    <style>
        #map {
            height: 600px;
            border-radius: 8px
        }
    </style>
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 mb-3">
                <div class="d-flex justify-content-between">
                    <h3 class="font-weight-bold">Edit Data Lokasi Pengobatan</h3>

                    <a href="{{ route('admin.lokasi-pengobatan.show', $lokasi_pengobatan) }}"
                        class="btn btn-primary btn-sm">
                        Kembali
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{ route('admin.lokasi-pengobatan.update', $lokasi_pengobatan) }}" method="post">
                        <div class="card-body">
                            <h4 class="card-title">Data Lokasi Pengobatan</h4>

                            @csrf
                            @method('PUT')

                            <div class="form-group">
                                <label for="nama">Nama</label>
                                <input type="text" name="nama"
                                    class="form-control @error('nama') is-invalid @enderror" id="nama"
                                    value="{{ old('nama', $lokasi_pengobatan->nama) }}" placeholder="Nama" required>

                                @error('nama')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="alamat">Alamat</label>
                                        <textarea name="alamat" class="form-control @error('alamat') is-invalid @enderror" id="alamat" placeholder="Alamat">{{ old('alamat', $lokasi_pengobatan->alamat) }}</textarea>

                                        @error('alamat')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="keterangan">Keterangan</label>
                                        <textarea name="keterangan" class="form-control @error('keterangan') is-invalid @enderror" id="keterangan"
                                            placeholder="Keterangan">{{ old('keterangan', $lokasi_pengobatan->keterangan) }}</textarea>

                                        @error('bobot')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="latitude">Latitude</label>
                                        <input type="text" name="latitude"
                                            class="form-control @error('latitude') is-invalid @enderror" id="latitude"
                                            value="{{ old('latitude', $lokasi_pengobatan->latitude) }}"
                                            placeholder="Latitude">

                                        @error('latitude')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-12 col-md-6">
                                    <div class="form-group">
                                        <label for="longitude">Longitude</label>
                                        <input type="text" name="longitude"
                                            class="form-control @error('longitude') is-invalid @enderror" id="longitude"
                                            value="{{ old('longitude', $lokasi_pengobatan->longitude) }}"
                                            placeholder="Longitude">

                                        @error('longitude')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <div id="map"></div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-end">
                            <input type="submit" value="Simpan" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('custom_js')
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>

    <script>
        let lat = document.querySelector('#latitude');
        let lng = document.querySelector('#longitude');

        var map = L.map('map').setView([{{ $lokasi_pengobatan->latitude }}, {{ $lokasi_pengobatan->longitude }}], 14);

        var marker = L.marker([{{ $lokasi_pengobatan->latitude }}, {{ $lokasi_pengobatan->longitude }}]).addTo(map);

        map.attributionControl.setPrefix('')
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);

        var geocoder = L.Control.geocoder({
                defaultMarkGeocode: false
            })
            .on('markgeocode', function(e) {
                var bbox = e.geocode.bbox;
                var poly = L.polygon([
                    bbox.getSouthEast(),
                    bbox.getNorthEast(),
                    bbox.getNorthWest(),
                    bbox.getSouthWest()
                ]).addTo(map);
                map.fitBounds(poly.getBounds());
            })
            .addTo(map);

        var markers = L.layerGroup().addTo(map);
        marker.addTo(markers)

        map.on('click', (event) => {
            markers.clearLayers();
            L.marker([event.latlng.lat, event.latlng.lng]).addTo(markers);

            lat.value = event.latlng.lat;
            lng.value = event.latlng.lng;
        });
    </script>
@endpush

resources/views/admin/lokasi-pengobatan/index.blade.php
@extends('layouts.admin')
@section('title', 'Kelola Data Lokasi Pengobatan')

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 mb-3">
                <div class="d-flex justify-content-between">
                    <h3 class="font-weight-bold">Kelola Data Lokasi Pengobatan</h3>

                    <a href="{{ route('admin.lokasi-pengobatan.create') }}" class="btn btn-primary btn-sm">
                        Tambah
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Daftar Lokasi Pengobatan</h4>
                        <div class="table-responsive">
                            <table class="table datatable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nama</th>
                                        <th>Alamat</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($data as $item)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $item->nama }}</td>
                                            <td>{{ $item->alamat }}</td>
                                            <td class="d-flex justify-content-end">
                                                <a href="{{ route('admin.lokasi-pengobatan.show', $item) }}"
                                                    class="btn btn-sm btn-success">Lihat</a>
                                                <a href="{{ route('admin.lokasi-pengobatan.edit', $item) }}"
                                                    class="btn btn-sm btn-warning mx-1">Edit</a>
                                                <a href="#" class="btn btn-sm btn-danger btn-delete"
                                                    data-id="{{ $item->id }}">Hapus</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('custom_html')
    <form action="#" method="post" id="delete-form">
        @csrf
        @method('DELETE')
    </form>
@endsection

@push('custom_js')
    <script>
        let deleteBtns = document.querySelectorAll('.btn-delete');
        deleteBtns.forEach((btn) => {
            btn.addEventListener('click', () => {
                let id = btn.getAttribute('data-id');

                Swal.fire({
                    title: 'Yakin Ingin Menghapus?',
                    text: "Yakin ingin menghapus data? Data yang dihapus tidak bisa dikembalikan lagi.",
                    icon: 'warning',
                    showCancelButton: true,
                    cancelButtonColor: '#3085d6',
                    confirmButtonColor: '#d33',
                    confirmButtonText: 'Hapus',
                    cancelButtonText: 'Batal',
                }).then((result) => {
                    if (result.isConfirmed) {
                        let form = document.querySelector('#delete-form');
                        form.setAttribute('action',
                            `{{ route('admin.lokasi-pengobatan.destroy', false) }}/${id}`);

                        form.submit();
                    }
                })
            });
        });
    </script>
@endpush

resources/views/admin/lokasi-pengobatan/show.blade.php
@extends('layouts.admin')
@section('title', 'Data Lokasi Pengobatan')

@section('custom_head')
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />

    <style>
        #map {
            height: 600px;
            border-radius: 8px
        }
    </style>
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 mb-3">
                <div class="d-flex justify-content-between">
                    <h3 class="font-weight-bold">Data Lokasi Pengobatan</h3>

                    <a href="{{ route('admin.lokasi-pengobatan.index') }}" class="btn btn-primary btn-sm">
                        Kembali
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="table-responsive">
                        <table class="table no-border-top">
                            <tbody>
                                <tr>
                                    <td>ID</td>
                                    <td><strong>{{ $lokasi_pengobatan->id }}</strong></td>
                                </tr>
                                <tr>
                                    <td>Nama</td>
                                    <td><strong>{{ $lokasi_pengobatan->nama }}</strong></td>
                                </tr>
                                <tr>
                                    <td>Alamat</td>
                                    <td><strong>{{ $lokasi_pengobatan->alamat }}</strong></td>
                                </tr>
                                <tr>
                                    <td>Keterangan</td>
                                    <td><strong>{{ $lokasi_pengobatan->keterangan }}</strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer d-flex justify-content-end">
                        <a href="{{ route('admin.lokasi-pengobatan.edit', $lokasi_pengobatan) }}"
                            class="btn btn-warning mr-1 btn-sm">Edit</a>
                        <a href="#" class="btn btn-danger btn-delete btn-sm">Hapus</a>
                    </div>
                </div>

                <div class="card mt-3">
                    <div id="map"></div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('custom_html')
    <form action="{{ route('admin.lokasi-pengobatan.destroy', $lokasi_pengobatan) }}" method="post" id="delete-form">
        @csrf
        @method('DELETE')
    </form>
@endsection

@push('custom_js')
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

    <script>
        let deleteBtn = document.querySelector('.btn-delete');
        deleteBtn.addEventListener('click', () => {

            Swal.fire({
                title: 'Yakin Ingin Menghapus?',
                text: "Yakin ingin menghapus data? Data yang dihapus tidak bisa dikembalikan lagi.",
                icon: 'warning',
                showCancelButton: true,
                cancelButtonColor: '#3085d6',
                confirmButtonColor: '#d33',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batal',
            }).then((result) => {
                if (result.isConfirmed) {
                    let form = document.querySelector('#delete-form');
                    form.submit();
                }
            })
        });
    </script>

    <script>
        var map = L.map('map').setView([{{ $lokasi_pengobatan->latitude }}, {{ $lokasi_pengobatan->longitude }}], 14);
        var marker = L.marker([{{ $lokasi_pengobatan->latitude }}, {{ $lokasi_pengobatan->longitude }}]).addTo(map);

        map.attributionControl.setPrefix('')
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);
    </script>
@endpush